name: CI

on: 
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup snakemake
      run: conda create -c bioconda -c conda-forge -n snakemake snakemake
    - name: Run tests
      run: |
        conda init
        conda activate snakemake
        snakemake --use-conda --directory .test || (for f in .test/logs/*; do echo $f; cat $f; done; for f in .test/logs/*/*; do echo $f; cat $f; done; exit 1)
